name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: romanian.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: romanian.pdf
